services:

  flask-backend:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./logs/flask:/app/logs
    env_file:
      - ./flask_app/.env
    environment:
      - FLASK_ENV=production

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
      - ./nginx/certbot_nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx  # Mount the entire logs directory
    depends_on:
      - flask-backend
      
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./nginx/certs:/etc/letsencrypt
  #     - ./nginx/www:/var/www/certbot
  #   depends_on:
  #     - nginx